### PR TITLE
Rename catalog-info.yaml to catalog-info.yml

### PR DESCRIPTION
**Pull request by ehats**
For consistency with other repos

### CODE REVIEW

**Comment by sorenmat** [comment]
FYI we will then be following a different 'standard' then the official backstage https://github.com/backstage/backstage/blob/master/catalog-info.yaml
Not sure if that matters..

**Comment by ehats** [comment]
I would have been fine with either, but wasn't it you guys who went for `.yml`?

See this commit from Jacob:
https://github.com/Tradeshift/github-emperor/commit/2cc3cc4a72159deb3b242073e8eb001d8f3de01c#diff-f5baf8bc9323d0970db3855dbb1a9e7c874b85e8df0c3d57ee39298eb6b75bf1R175

My understanding is that the rationale was that Github actions only accepts `.yml`, so let's stick with `.yml` everywhere

**Comment by ehats** [comment]
@Tradeshift/developer-productivity please review

**Comment by ehats** [comment]
@Tradeshift/developer-productivity please review

**Review by fardin01 — APPROVED** [review]
🎖️

**Pull request merged**
